package com.leagueofteams.riotconnector.leagueoflegends.client.constants

enum class Language (val code: String, val language: String){

    CZECH_REPUBLIC("cs_CZ", "Czech"),
    GREECE("el_GR", "Greek"),
    POLAND("pl_PL", "Polish"),
    ROMANIA("ro_RO", "Romanian"),
    HUNGARY("hu_HU", "Hungarian"),
    UNITED_KINGDOM("en_GB", "English"),
    GERMANY("de_DE", "German"),
    SPAIN("es_ES", "Spanish"),
    ITALY("it_IT", "Italian"),
    FRANCE("fr_FR", "French"),
    JAPAN("ja_JP", "Japanese"),
    KOREA("ko_KR", "Korean"),
    MEXICO("es_MX", "Spanish"),
    ARGENTINA("es_AR", "Spanish"),
    BRAZIL("pt_BR", "Portuguese"),
    UNITED_STATES("en_US", "English"),
    AUSTRALIA("en_AU", "English"),
    RUSSIA("ru_RU", "Russian"),
    TURKEY("tr_TR", "Turkish"),
    MALAYSIA("ms_MY", "Malay"),
    REPUBLIC_OF_THE_PHILIPPINES("en_PH", "English"),
    SINGAPORE("en_SG", "English"),
    THAILAND("th_TH", "Thai"),
    VIET_NAM("vn_VN", "Vietnamese"),
    INDONESIA("id_ID", "Indonesian"),
    MALAYSIA_CH("zh_MY", "Chinese"),
    CHINA("zh_CN", "Chinese"),
    TAIWAN("zh_TW", "Chinese"),
}